### PR TITLE
`AutoActivate()` should not hide a component's default service

### LINKED ISSUE #1450: `AutoActivate()` hides a registration's default "self" service
## Describe the Bug

A registration like `builder.Register<A>()` defaults to exposing the typed service `A` on the component.

Adding `AutoActivate()` to the registration hides this default. Since the name `AutoActivate()` doesn't suggest that it has anything to do with exposed services, this seems like a bug or rough edge in the API.

## Steps to Reproduce

```c#
public class StartableTests
{
    [Fact]
    public void AutoActivate_DoesNotHideDefaultSelfService()
    {
        var builder = new ContainerBuilder();
        builder.RegisterType<MyComponent2>().AutoActivate();
        using var container = builder.Build();
        Assert.True(container.IsRegistered<MyComponent2>());
    }
```

The test can be made to succeed by adding `AsSelf()` to the registration.

## Expected Behavior

`AutoActivate()` would not alter the services exposed by the component in a user-visible manner.

## Dependency Versions

`develop` branch.

## Additional Info

Happy to try to fix this and send a PR, just opening this first to gauge whether it's a known issue or by design. Not in any way blocked on this :-)

### PR DESCRIPTION
**Pull request by nblumhardt**
Fixes #1450.

### CODE REVIEW

**Comment by nblumhardt** [comment]
Not sure why AppVeyor is reporting this as non-mergeable; is that just a policy-driven thing, or is there some kind of conflict lurking? (Hoping I targeted the right branch?)

File: src/Autofac/RegistrationExtensions.cs [hunk 1]
```diff
@@ -69,6 +69,11 @@ public static IRegistrationBuilder<T, SimpleActivatorData, SingleRegistrationSty
 
         rb.SingleInstance();
 
+        // https://github.com/autofac/Autofac/issues/1102
+        // Single instance registrations with any custom activation phases (i.e. activation handlers) need to be auto-activated,
+        // so that other behavior (such as OnRelease) that expects 'normal' object lifetime behavior works as expected.
+        rb.RegistrationData.AddService(new AutoActivateService());
```
Comment (nblumhardt) [inline src/Autofac/RegistrationExtensions.cs:75]: This simplification wasn't possible prior to the other fix, as it would have broken default service logic.

File: src/Autofac/RegistrationExtensions.cs [hunk 2]
```diff
@@ -79,21 +84,6 @@ public static IRegistrationBuilder<T, SimpleActivatorData, SingleRegistrationSty
 
             activator.DisposeInstance = rb.RegistrationData.Ownership == InstanceOwnership.OwnedByLifetimeScope;
 
-            // https://github.com/autofac/Autofac/issues/1102
-            // Single instance registrations with any custom activation phases (i.e. activation handlers) need to be auto-activated,
-            // so that other behavior (such as OnRelease) that expects 'normal' object lifetime behavior works as expected.
-            if (rb.ResolvePipeline.Middleware.Any(s => s.Phase == PipelinePhase.Activation))
-            {
-                var autoStartService = rb.RegistrationData.Services.First();
```
Comment (nblumhardt) [inline src/Autofac/RegistrationExtensions.cs:87]: The bug here is due to the possibility that there are multiple registrations for this service; resolving it won't guarantee that we end up with the same component (and in fact, some unrelated random thing could end up unexpectedly activated :-))

**Comment by tillig** [comment]
I'm not sure why it's saying that, but I'm on holiday until next week so I won't be able to figure it out until then. It... should just build. 🤷‍♂️

**Comment by tillig** [comment]
I've poked around on this trying to figure out why AppVeyor won't merge this properly and I've not found anything helpful. I'll just test it locally and call it good. I think the changes are fine. I want to move to GitHub Actions anyway, so it's not worth fighting too hard with the AppVeyor issue.

**Review by tillig — APPROVED** [review]
Looks good! I verified the changes on my local machine rather than fighting AppVeyor. It all builds and tests out correctly. I'll see if I can get this merged and get a 0.0.1 release out the door shortly.

**Comment by nblumhardt** [comment]
Great - thanks! :+1:
